name: love
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  after_layout: ^1.2.0
  animated_notch_bottom_bar: ^1.0.1
  animations: ^2.0.11
  audio_video_progress_bar: ^2.0.1
  auto_size_text: ^3.0.0
  confetti: ^0.7.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  firebase_messaging: ^14.7.10
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11
  lazy_load_indexed_stack: ^1.1.0
  lottie: ^3.0.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  timer_count_down: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/icons/
    - assets/audio/
