name: love
description: 'Una app para mi novia <3'
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.1

dependencies:
  after_layout: ^1.2.0
  animated_notch_bottom_bar: ^1.0.3
  animations: ^2.0.11
  auto_size_text: ^3.0.0
  confetti: ^0.8.0
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  firebase_messaging: ^15.1.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  just_audio: ^0.9.41
  just_audio_background: ^0.0.1-beta.13
  lazy_load_indexed_stack: ^1.1.0
  lottie: ^3.1.2
  rxdart: ^0.28.0
  settings_ui: ^2.0.2
  shared_preferences: ^2.3.2
  smooth_page_indicator: ^1.2.0+3
  timer_count_down: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  icons_launcher: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Bruno
      fonts:
        - asset: assets/fonts/Bruno-Regular.ttf
    - family: Folklore
      fonts:
        - asset: assets/fonts/IMFellDWPica-Italic.ttf
  assets:
    - assets/animations/
    - assets/icons/
    - assets/audio/
    - assets/images/

icons_launcher:
  image_path: "assets/icon.png"
  platforms:
    android:
      enable: true
      adaptive_background_color: "#8671f1"
      adaptive_foreground_image: "assets/icon.png"
