name: love
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animated_notch_bottom_bar: ^1.0.1
  dynamic_color: ^1.6.9
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
